name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip install setuptools svgwrite wheel
      - run: pip install pytest
      - run: env
      - run: env | grep ci
      - run: env | grep CI
      - run: pytest
