name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell
    - run: ruff check --output-format=github
    - run: ruff format
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip install setuptools svgwrite wheel
      - run: pip install pytest
      - run: env
      - run: env | grep ci
      - run: env | grep CI  # $CI == true
      - run: pytest
